import { buildRoadmapPrompt, buildSimplifiedRoadmapPrompt } from "./roadmap.promptBuilder.js";

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const MODEL_PRIMARY = "gemini-2.5-flash";
const MODEL_SECONDARY = "gemini-1.5-flash";

/**
 * Calls Gemini API directly with retry logic, exponential backoff, and model fallback.
 */
async function callGeminiAPI(prompt, model = MODEL_PRIMARY) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`;
  
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [{ text: prompt }],
        },
      ],
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`STATUS_${response.status}: ${errText}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new Error("No text returned from Gemini API");
  }

  return text;
}

/**
 * Cleans the Gemini output to extract a valid JSON string.
 */
function cleanAndParseJSON(text) {
  let cleanText = text
    .replace(/```json/g, "")
    .replace(/```/g, "")
    .trim();

  const start = cleanText.indexOf("{");
  const end = cleanText.lastIndexOf("}");

  if (start !== -1 && end !== -1) {
    cleanText = cleanText.substring(start, end + 1);
  }

  return JSON.parse(cleanText);
}

/**
 * Service function to handle the roadmap generation pipeline.
 */
export async function generateRoadmapService({ type, query, level }) {
  let attempt = 1;
  const maxAttempts = 3;
  let delay = 1000;
  let useFallbackModel = false;
  let useSimplifiedPrompt = false;

  while (attempt <= maxAttempts) {
    const currentModel = useFallbackModel ? MODEL_SECONDARY : MODEL_PRIMARY;
    const currentPrompt = useSimplifiedPrompt 
      ? buildSimplifiedRoadmapPrompt({ type, query, level })
      : buildRoadmapPrompt({ type, query, level });

    console.log(`[Roadmap Service] Attempt ${attempt}/${maxAttempts} using model: ${currentModel}`);

    try {
      const rawResponse = await callGeminiAPI(currentPrompt, currentModel);
      const parsedData = cleanAndParseJSON(rawResponse);
      
      // Validation check
      if (!parsedData.title || !parsedData.milestones || parsedData.milestones.length === 0) {
        throw new Error("Incomplete JSON output generated by AI");
      }

      console.log(`[Roadmap Service] Generation succeeded on attempt ${attempt}`);
      return parsedData;

    } catch (error) {
      console.warn(`[Roadmap Service] Attempt ${attempt} failed: ${error.message}`);
      
      if (attempt === maxAttempts) {
        throw new Error("Roadmap generation failed after exhausting all retry strategies.");
      }

      // Adjust strategy for next retry
      if (error.message.includes("STATUS_503") || error.message.includes("STATUS_429")) {
        useFallbackModel = true; // Swap model to secondary
      } else {
        useSimplifiedPrompt = true; // Use simpler prompt to fit tokens / structures
      }

      // Exponential backoff
      await new Promise((resolve) => setTimeout(resolve, delay));
      delay *= 2;
      attempt++;
    }
  }
}
